global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "alerting_rules.yml"
  # - "recording_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Application metrics
  - job_name: 'app'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 5s
    metrics_path: '/metrics'
    params:
      format: ['prometheus']
    basic_auth:
      username: ${PROMETHEUS_USERNAME}
      password: ${PROMETHEUS_PASSWORD}
    tls_config:
      ca_file: /etc/ssl/certs/ca.pem
      cert_file: /etc/ssl/certs/prometheus.crt
      key_file: /etc/ssl/private/prometheus.key

  # Node.js application health
  - job_name: 'nodejs'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 10s
    metrics_path: '/health/metrics'

  # Database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # System metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Nginx metrics (if enabled)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: '/status'
    params:
      format: ['prometheus']

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s

  # Custom business metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 60s
    metrics_path: '/metrics/business'

  # Kubernetes service discovery
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: (.+)
        target_label: app
        replacement: $1
      - source_labels: [__meta_kubernetes_pod_container_port_number]
        regex: '3000'
        action: keep
    scrape_interval: 15s
    metrics_path: '/metrics'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
