auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  tls_config:
    cert_file: /etc/ssl/certs/loki.crt
    key_file: /etc/ssl/private/loki.key

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    s3:
      bucketnames: my-loki-bucket
      endpoint: s3.amazonaws.com
      region: us-east-1
      access_key_id: ${AWS_ACCESS_KEY_ID}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  replication_factor: 3
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used and thus prioritize
# fixes and improvements.
#
# To disable analytics, uncomment the following line:
#analytics:
#  reporting_enabled: false
